config/routes.rb
Rails.application.routes.draw do
  resources :sources do
    collection do
      post :import
    end
  end

  root to: 'root#home'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :artists, except: [ :edit, :update, :destroy ]
  resources :venues,  except: [ :edit, :update, :destroy ]
  resources :events,  except: [ :destroy ] do
    collection do
      post :import
    end
  end

  namespace :admin do
    get 'dashboard', to: 'dashboard#home'
    get 'load_google_calendars', to: 'dashboard#load_google_calendars'

    # get 'authorize_all', to: 'dashboard#authorize_all'
    # get 'delete_all_ads', to: 'dashboard#delete_all_ads'
    # get 'delete_all_banners', to: 'dashboard#delete_all_banners'

    resources :users

    resources :ads do
      collection do
        delete :destroy_all
      end
    end

    resources :banners do
      collection do
        delete :destroy_all
      end
    end

    resources :csv_calendars

    resources :artists

    resources :venues

    resources :lists

    resources :events do
      member do
        patch :authorize
        patch :unauthorize
      end

      collection do
        patch :authorize_all
      end
    end
  end

  get '/blog', to: 'static_pages#blog', as: 'blog'
end

app/controllers/admin/dashboard_controller.rb
require 'nokogiri'
require 'digest/sha1'
require 'open-uri'

class Admin::DashboardController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  before_action :authenticate_user!

  expose(:lists) { Admin::List.all }
  expose(:banner) { Admin::Banner.new }
  expose(:ad) { Admin::Ad.new }
  expose(:csv_calendar) { Admin::CsvCalendar.new }
  expose(:csv_calendars) { Admin::CsvCalendar.all }
  
  def home
    @events = Event.order(start_time: :desc)
    @events_authorization = Event.where(authorized: false).order(start_time: :desc)
  end

  def load_google_calendars
    load_cals
    redirect_to admin_dashboard_path
  end

  private

    def authorize_all_events
      Event.authorize_all
    end

    def load_cals
      Digger::Calendar.load
    end
end

app/controllers/dashboard_controller.rb
require 'nokogiri'
require 'digest/sha1'
require 'open-uri'

class DashboardController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  before_action :authenticate_user!

  expose(:lists) { List.all }
  
  def home
    @events = Event.all.order(begin_at: :desc)
    @events_authorization = Event.where(authorized: nil).order(begin_at: :desc)
    @csv_calendar = CsvCalendar.new
    @csv_calendars = CsvCalendar.all
    @ad = Ad.new
    @banner = Banner.new
  end

  def load_google_calendars
    load_cals
    redirect_to dashboard_path
  end

  def authorize_all
    authorize_all_events
    redirect_to dashboard_path
  end

  def delete_all_ads
    Ad.delete_all
    redirect_to dashboard_path
  end

  def delete_all_banners
    Banner.delete_all
    redirect_to dashboard_path
  end

  private

    def authorize_all_events
      Event.where(authorized: nil).each do |event|
        event.update_columns authorized: true
      end
    end

    def load_cals
      Digger::Calendar.load
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboard/_ad_upload.html.erb
<%= link_to 'Delete All Ads', destroy_all_admin_ads_path, method: :delete,
    class: 'btn btn-danger pull-right', data: { confirm: 'Are you sure?' } %>

<h3>Ad Upload</h3>

<%= render 'admin/ads/form' %>

app/views/admin/dashboard/_banner_upload.html.erb
<%= link_to 'Delete All Banners', destroy_all_admin_banners_path, method: :delete,
    class: 'btn btn-danger pull-right', data: { confirm: 'Are you sure?' } %>

<h3>Banner Upload</h3>

<%= render 'admin/banners/form' %>

app/views/admin/dashboard/_csv_upload.html.erb
<h3>CSV Upload</h3>
<%= render 'admin/csv_calendars/form' %>

app/views/admin/dashboard/_event_authorization.html.erb
<h3>Unauthorized Events</h3>
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <%= link_to 'Import External Calendars', new_source_path,
          id: 'google-cal-btn', class: 'btn btn-primary form-control' %>
    </div>
  </div>

  
</div>
<table class="table table-striped">
  <tr>
    <th class="col-md-3">Date</th>
    <th class="col-md-7">Name</th>
  </tr>
  
  <% @events_authorization.order('start_time ASC').each do |event| %>
    <tr>
      <td><small><%= event.start_time.strftime('%Y-%m-%d %H:%M') %></small></td>
      <td><%= link_to event.title, edit_event_path(event) %></td>
      
    </tr>
  <% end %>
</table>

app/views/admin/dashboard/_events.html.erb
<h3>Events</h3>
<p class="form-control" disabled>
  <strong>Total : </strong><span class="label label-primary"><%= Event.count %></span>
  <strong>Total Regular : </strong><span class="label label-default"><%= Event.where('recurring = ?', false).count %></span>
  <strong>Total Recurring : </strong><span class="label label-warning"><%= Event.where('recurring = ?', true).count %></span>
</p>
<table class="table table-striped">
  <tr>
    <th class="col-md-3">Date</th>
    <th class="col-md-7">Name</th>
    <th class="col-md-2">Recurring</th>
  </tr>
  
  <% @events.order('start_time DESC').each do |event| %>
    <tr>
      <% if event.authorized %>
        <td><small><%= event.start_time.strftime('%H:%M %d-%m-%Y') %></small></td>
        <td><%= link_to event.title, edit_admin_event_path(event) %></td>
        <td><%= event.recurring? ? "<strong class=\"text-success\">Yes</strong>".html_safe : "<strong class=\"text-danger\">No</strong>".html_safe %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/admin/dashboard/_lists.html.erb
<h1>Lists</h1>

<ul class="no-bullet no-padding">
  <% lists.each do |list| %>
    <%= render list %>
  <% end %>
</ul>

<br>

<%= link_to 'New List', new_admin_list_path %>

app/views/admin/dashboard/home.html.erb
<div role="tabpanel">
  <ul id="dashboard-tabs" class="nav nav-tabs" role="tablist">
    <li>
      <%= link_to 'Events', '#events', role: 'tab', data: { toggle: 'tab' } %>
    </li>

    <li role="presentation">
      <%= link_to 'Lists', '#lists', role: 'tab', data: { toggle: 'tab' } %>
    </li>

    <li role="presentation" class="active">
      <%= link_to 'Authorization', '#event-authorization', role: 'tab', data: { toggle: 'tab' } %>
    </li>

    <li role="presentation">
      <%= link_to 'Banner Upload', '#banner-upload', role: 'tab', data: { toggle: 'tab' } %>
    </li>

    <li role="presentation">
      <%= link_to 'Ad Upload', '#ad-upload', role: 'tab', data: { toggle: 'tab' } %>
    </li>
    
    <li role="presentation">
      <%= link_to 'CSV Upload', '#csv-upload', role: 'tab', data: { toggle: 'tab' } %>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="events">
      <%= render 'admin/dashboard/events' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="lists">
      <%= render 'admin/dashboard/lists' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="banner-upload">
      <%= render 'admin/dashboard/banner_upload' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="ad-upload">
      <%= render 'admin/dashboard/ad_upload' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="csv-upload">
      <%= render 'admin/dashboard/csv_upload' %>
    </div>

    <div role="tabpanel" class="tab-pane active" id="event-authorization">
      <%= render 'admin/dashboard/event_authorization' %>
    </div>
  </div>
</div>