config/routes.rb
Rails.application.routes.draw do
  resources :sources do
    collection do
      post :import
    end
  end

  root to: 'root#home'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :artists, except: [ :edit, :update, :destroy ]
  resources :venues,  except: [ :edit, :update, :destroy ]
  resources :events,  except: [ :destroy ] do
    collection do
      post :import
    end
  end

  namespace :admin do
    get 'dashboard', to: 'dashboard#home'
    get 'load_google_calendars', to: 'dashboard#load_google_calendars'

    # get 'authorize_all', to: 'dashboard#authorize_all'
    # get 'delete_all_ads', to: 'dashboard#delete_all_ads'
    # get 'delete_all_banners', to: 'dashboard#delete_all_banners'

    resources :users

    resources :ads do
      collection do
        delete :destroy_all
      end
    end

    resources :banners do
      collection do
        delete :destroy_all
      end
    end

    resources :csv_calendars

    resources :artists

    resources :venues

    resources :lists

    resources :events do
      member do
        patch :authorize
        patch :unauthorize
      end

      collection do
        patch :authorize_all
      end
    end
  end

  get '/blog', to: 'static_pages#blog', as: 'blog'
end

app/views/shared/_advertisement.haml
%section#ads
  - Admin::Ad.all.each do |ad|
    = link_to image_tag(ad.image(:medium), size: '300x300', alt: :advertisement, class: 'ad'), ad.url
/
  <div
  class="fb-like-box"
  data-href="https://www.facebook.com/PinUpGattawa"
  data-width="100%"
  data-height="250px"
  data-colorscheme="light"
  data-show-faces="true"
  data-header="false"
  data-stream="false"
  data-show-border="false">
  </div>

app/views/shared/_banner.haml
- unless @banner.nil?
  %section#banner
    = link_to image_tag(@banner.image, size: '627x68', alt: :banner, class: 'banner'), @banner.url

app/views/shared/_facebook.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= ENV['FACEBOOK_APP_ID'] %>',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top{ role: "navigation" }
  = link_to 'Radiant Sands', root_path, id: 'logo', class: 'navbar-brand'

  %button.navbar-toggler{type: 'button', data: { toggle: 'collapse', target: '#navbar-nav-dropdown'}, 'aria-controls': 'navbar-nav-dropdown', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation' }
    %span.navbar-toggler-icon

  .navbar-collapse.collapse#navbar-nav-dropdown
    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to events_path, class: 'nav-link' do
          %i.flaticon.flaticon-election
          Calendar

      %li.nav-item
        = link_to artists_path, class: 'nav-link' do
          %i.flaticon.flaticon-artist2
          Artists

      %li.nav-item
        = link_to venues_path, class: 'nav-link' do
          %i.flaticon.flaticon-theater5
          Venues

    %form.form-inline.my-2
      - if user_signed_in? && current_user.admin?
        = link_to 'Dashboard', admin_dashboard_path, class: "btn btn-flat btn-primary"
      - elsif user_signed_in?
        = link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-primary'
      - else
        = link_to 'Sign in', new_user_session_path, class: 'btn btn-primary mr-2'
        = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary'

app/views/shared/_sidebar.haml
%p{:style => "text-align: justify;"}
  Radiant Sands - your complete, comprehensive and collaborative cultural events calendar for the Ottawa-Gatineau metropolitan region.
= yield :filters