config/routes.rb
Rails.application.routes.draw do
  resources :sources do
    collection do
      post :import
    end
  end

  root to: 'root#home'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :artists, except: [ :edit, :update, :destroy ]
  resources :venues,  except: [ :edit, :update, :destroy ]
  resources :events,  except: [ :destroy ] do
    collection do
      post :import
    end
  end

  namespace :admin do
    get 'dashboard', to: 'dashboard#home'
    get 'load_google_calendars', to: 'dashboard#load_google_calendars'

    # get 'authorize_all', to: 'dashboard#authorize_all'
    # get 'delete_all_ads', to: 'dashboard#delete_all_ads'
    # get 'delete_all_banners', to: 'dashboard#delete_all_banners'

    resources :users

    resources :ads do
      collection do
        delete :destroy_all
      end
    end

    resources :banners do
      collection do
        delete :destroy_all
      end
    end

    resources :csv_calendars

    resources :artists

    resources :venues

    resources :lists

    resources :events do
      member do
        patch :authorize
        patch :unauthorize
      end

      collection do
        patch :authorize_all
      end
    end
  end

  get '/blog', to: 'static_pages#blog', as: 'blog'
end

app/models/admin/csv_calendar.rb
class Admin::CsvCalendar < ActiveRecord::Base
  has_one_attached :file
end

app/controllers/admin/csv_calendars_controller.rb
require 'csv'
require "open-uri"

class Admin::CsvCalendarsController < ApplicationController

  expose(:csv_calendar, attributes: :csv_calendar_params) { params[:id].nil? ? Admin::CsvCalendar.new : Admin::CsvCalendar.find(params[:id]) }
  expose(:csv_calendars) { Admin::CsvCalendar.all }

  before_action :authenticate_user!

  respond_to :html

  def create
    if params[:admin_csv_calendar].nil?
      redirect_to admin_dashboard_path
    else
      self.csv_calendar = Admin::CsvCalendar.new(csv_calendar_params)
      if csv_calendar.save
        import_events_from_calendar
        redirect_to admin_dashboard_path
      else
        redirect_to admin_dashboard_path
      end
    end
  end

  def update
    csv_calendar.update(csv_calendar_params)
    redirect_to admin_dashboard_path
  end

  def destroy
    csv_calendar.destroy
    redirect_to admin_dashboard_path
  end

  private

    def csv_calendar_params
      params.require(:admin_csv_calendar).permit(:file)
    end

    def import_events_from_calendar
      CsvCalendarLoader.perform_async(csv_calendar.id)
    end
end

app/helpers/csv_calendars_helper.rb
module CsvCalendarsHelper
end

app/views/admin/csv_calendars/_csv_calendar.html.erb
<%= link_to csv_calendar.created_at, csv_calendar %>
<%= link_to 'Import', '#', class: 'btn btn-primary' %>

app/views/admin/csv_calendars/_form.html.erb
        <%= form_tag import_events_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import CSV" %>
        <% end %>

app/views/admin/csv_calendars/_formold.html.erb
 <%= form_for csv_calendar, html: { multipart: true } do |f| %>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <% f.label :file %><p><span class="label label-primary">Date</span><span class="label label-primary">Name</span><span class="label label-primary">Time</span><span class="label label-primary">Price</span><span class="label label-primary">Description</span><span class="label label-primary">Referrer URL</span><span class="label label-primary">Referrer</span></p>
        <div class="input-group">
         <%= link_to 'Browse...', '#', id: 'file-upload-btn', class: 'input-group-addon btn btn-default' %>
          <span id="file-upload-label" class="form-control"></span>
          <%= f.file_field :file, id: 'file-upload', style: 'display: none;' %>
        </div>
        <%= display_error_for csv_calendar, :file %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-group">
        <%= f.submit 'Upload CSV File', id: 'cal-upload-btn', class: 'btn btn-primary form-control' %>
      </div>
    </div>
  </div>

 <% end %>

app/views/admin/csv_calendars/edit.html.erb
<h1>Editing csv_calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_csv_calendar_path(csv_calendar) %> |
<%= link_to 'Back', admin_csv_calendars_path %>

app/views/admin/csv_calendars/index.html.erb
<h1>Listing csv_calendars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% csv_calendars.each do |csv_calendar| %>
      <tr>
        <td><%= link_to 'Show', admin_csv_calendar_path(csv_calendar) %></td>
        <td><%= link_to 'Edit', edit_admin_csv_calendar_path(csv_calendar) %></td>
        <td><%= link_to 'Destroy', admin_csv_calendar_path(csv_calendar), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv calendar', new_csv_calendar_path %>

app/views/admin/csv_calendars/new.html.erb
<h1>New csv_calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_csv_calendars_path %>

app/views/admin/csv_calendars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_csv_calendar_path(csv_calendar) %> |
<%= link_to 'Back', admin_csv_calendars_path %>